import { useEffect, useState } from 'react';
import { Compass, Home as HomeIcon, Inbox as InboxIcon, Plus, UserRound, Bell, Sparkles } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import Welcome from './Welcome'; import Home from './Home'; import Discover from './Discover'; import Inbox from './Inbox'; import Profile from './Profile'; import Workspace from './Workspace'; import CreateFlow from './CreateFlow';
import type { Page, ScreenProps } from './types';

function pathPage(path:string):Page{return path.includes('workspace')?'workspace':path.includes('discover')?'discover':path.includes('inbox')?'inbox':path.includes('profile')?'profile':'home'}
export default function App(){
 const router=useNavigate(), location=useLocation(); const [entered,setEntered]=useState(()=>sessionStorage.getItem('circle:entered')==='1'||location.pathname!=='/'); const [create,setCreate]=useState<'create'|'drafts'|null>(null); const [toast,setToast]=useState(''); const [navCompact,setNavCompact]=useState(false); const page=pathPage(location.pathname);
 useEffect(()=>{if(!entered)return; if(location.pathname==='/') router('/home',{replace:true})},[entered,location.pathname,router]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(timer)},[toast]);
 useEffect(()=>{let previous=window.scrollY;let ticking=false;const onScroll=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const current=window.scrollY;if(current>previous+5)setNavCompact(true);else if(current<previous-5)setNavCompact(false);previous=current;ticking=false})};window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
 const navigate=(next:Page)=>{router(`/${next}`);window.scrollTo({top:0,behavior:'smooth'})};
 const props:ScreenProps={notify:setToast,navigate,openCreate:()=>setCreate('create'),openDrafts:()=>setCreate('drafts')};
 if(!entered)return <Welcome onStart={()=>{sessionStorage.setItem('circle:entered','1');setEntered(true);router('/home')}}/>;
 return <div className={`app-shell page-${page} ${create?'create-open':''}`}><aside className="side-nav"><button className="brand" onClick={()=>navigate('home')} aria-label="Creative Circle home"><i/> <span>Creative<br/>Circle</span></button><nav aria-label="Primary navigation">{[{p:'home' as Page,n:'Home',i:<HomeIcon/>},{p:'discover' as Page,n:'Discover',i:<Compass/>},{p:'create' as const,n:'Create',i:<Plus/>},{p:'inbox' as Page,n:'Inbox',i:<InboxIcon/>},{p:'profile' as Page,n:'Profile',i:<UserRound/>}].map(x=><button key={x.n} aria-label={x.n} aria-expanded={x.p==='create'?Boolean(create):undefined} className={`${x.p===page?'active':''} ${x.p==='create'?'create-nav':''}`} aria-current={x.p===page?'page':undefined} onClick={()=>x.p==='create'?setCreate('create'):navigate(x.p)}>{x.i}<span>{x.n}</span></button>)}</nav><button className={`workspace-nav ${page==='workspace'?'active':''}`} onClick={()=>navigate('workspace')}><Sparkles/><span>My workspace</span></button><div className="side-person"><img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80" alt="Sample profile"/><span><b>Jordan K.</b><small>UI preview</small></span><Bell/></div></aside>
 <div className="mobile-brand"><button className="brand" onClick={()=>navigate('home')} aria-label="Creative Circle home"><i/><span>Creative Circle</span></button><button onClick={()=>setToast('No new notifications in this UI preview.')} className="icon-button" aria-label="Notifications"><Bell/></button></div>
 <div className="preview-banner" role="note">UI preview <span>Sample content · local interactions</span></div>
 <div className="app-content">{page==='home'?<Home {...props}/>:page==='discover'?<Discover {...props}/>:page==='inbox'?<Inbox {...props}/>:page==='profile'?<Profile {...props}/>:<Workspace {...props}/>}</div>
 <nav className={`bottom-nav ${navCompact?'is-compact':''}`} aria-label="Primary navigation">{[{p:'home' as Page,n:'Home',i:<HomeIcon/>},{p:'discover' as Page,n:'Discover',i:<Compass/>},{p:'create' as const,n:'Create',i:<Plus/>},{p:'inbox' as Page,n:'Inbox',i:<InboxIcon/>},{p:'profile' as Page,n:'Profile',i:<UserRound/>}].map(x=><button key={x.n} aria-label={x.n} aria-expanded={x.p==='create'?Boolean(create):undefined} className={`${x.p===page?'active':''} ${x.p==='create'?'create-nav':''}`} aria-current={x.p===page?'page':undefined} onClick={()=>x.p==='create'?setCreate('create'):navigate(x.p)}>{x.i}<span>{x.n}</span></button>)}</nav>
 {create&&<CreateFlow initialDrafts={create==='drafts'} onClose={()=>setCreate(null)} notify={setToast}/>} {toast&&<div className="toast" role="status">{toast}</div>}</div>
}
